name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    name: My Workflow Run  # Name of the job
    steps:
      - name: Trigger Event
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Runner OS
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Branch and Repository
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cloned Repository
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Ready to Test
        run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Job Status
        run: echo "🍏 This job's status is ${{ job.status }}."